# Generated by Django 4.2.2 on 2023-07-04 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('footballapp', '0002_competition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('shortName', models.CharField(blank=True, max_length=255, null=True)),
                ('tla', models.CharField(blank=True, max_length=255, null=True)),
                ('crest', models.URLField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballapp.area')),
            ],
        ),
    ]
