# Generated by Django 4.2.2 on 2023-07-04 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('footballapp', '0003_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utcDate', models.DateTimeField()),
                ('status', models.CharField(max_length=255)),
                ('minute', models.IntegerField(blank=True, null=True)),
                ('injuryTime', models.IntegerField(blank=True, null=True)),
                ('attendance', models.IntegerField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('matchDay', models.IntegerField()),
                ('stage', models.CharField(blank=True, max_length=255)),
                ('group', models.CharField(blank=True, max_length=255, null=True)),
                ('scoreHome', models.CharField(blank=True, max_length=255, null=True)),
                ('scoreAway', models.CharField(blank=True, max_length=255, null=True)),
                ('awayTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='footballapp.team')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballapp.competition')),
                ('homeTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='footballapp.team')),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
    ]
